require("meow.review").setup({})

local opts = { remap = true, silent = true }

vim.keymap.set({ "n", "v" }, "<leader>ra", "<Plug>(MeowReviewAdd)", opts)
vim.keymap.set({ "n", "v" }, "<leader>rd", "<Plug>(MeowReviewDelete)", opts)
vim.keymap.set("n", "<leader>re", "<Plug>(MeowReviewEdit)", opts)
vim.keymap.set("n", "<leader>rv", "<Plug>(MeowReviewView)", opts)
vim.keymap.set("n", "<leader>rE", "<Plug>(MeowReviewExport)", opts)
vim.keymap.set("n", "<leader>rX", "<Plug>(MeowReviewExportAndClear)", opts)
vim.keymap.set("n", "<leader>rf", "<Plug>(MeowReviewExportFile)", opts)
vim.keymap.set("n", "<leader>rc", "<Plug>(MeowReviewClear)", opts)
vim.keymap.set("n", "<leader>rg", "<Plug>(MeowReviewGoto)", opts)
vim.keymap.set("n", "<leader>rG", "<Plug>(MeowReviewGotoFile)", opts)
vim.keymap.set("n", "<leader>rt", "<Plug>(MeowReviewGotoType)", opts)
vim.keymap.set("n", "<leader>rR", "<Plug>(MeowReviewResolve)", opts)
vim.keymap.set("n", "<leader>rA", "<Plug>(MeowReviewResolveAll)", opts)
vim.keymap.set("n", "<leader>rr", "<Plug>(MeowReviewReload)", opts)
vim.keymap.set("n", "<leader>rV", "<Plug>(MeowReviewValidate)", opts)
vim.keymap.set("n", "]r", "<Plug>(MeowReviewNext)", opts)
vim.keymap.set("n", "[r", "<Plug>(MeowReviewPrev)", opts)
